In [2]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


In [5]:
arr[0]

1

# Numpy less memory than Python

In [25]:
import sys
b = range(1000)
print(b[9])
print(len(b))
print(sys.getsizeof(5))
print(sys.getsizeof(5)*len(b))

9
1000
28
28000


In [27]:
c = np.arange(1000)
print(c.size)
print(c.size * c.itemsize)

1000
8000


# Numpy is faster than Python

In [28]:
# for checking how fast Numpy run and how memory it uses; 
import time

In [29]:
size = 100000

In [30]:
# Python
L1 = range(size)
L2 = range(size)
# Numpy
A1 = np.arange(size)
A2 = np.arange(size)

In [31]:
start = time.time()
result = [(x+y) for x, y in zip(L1, L2)]
result = [(x+y) for x, y in zip(L1, L2)]
print("Python list took: ", (time.time() - start) * 1000)

Python list took:  24.46293830871582


In [35]:
start = time.time()
result = A1 + A2
result = A1 + A2
print("Numpy array took: ", (time.time() - start) * 1000)

Numpy array took:  0.5841255187988281


In [37]:
A1 = np.arange(10)
A2 = np.arange(10)
print(A1)

result = A1 + A2

print(result)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


# 2-dimension array

In [40]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
a = np.array([[1, 2, 3], [3, 4], [5, 6], [7, 8]])
print(a)
a.ndim
a.shape

[list([1, 2, 3]) list([3, 4]) list([5, 6]) list([7, 8])]


(4,)

In [50]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(a)
a.ndim
a.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


(4, 2)

In [51]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype = np.float64)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [52]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype = np.complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j]]


In [53]:
print(a.dtype)

complex128


In [54]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
print(np.char.add(["abc", 'de'], ['123', '45']))

['abc123' 'de45']


In [62]:
print(np.char.center("Hello", 10, fillchar = "-"))

--Hello---


In [63]:
print(np.char.center("Hello", 20))

       Hello        


In [66]:
print(np.char.capitalize("hello world"))

Hello world


In [67]:
print(np.char.title("how are you doing?"))

How Are You Doing?


In [68]:
print(np.char.lower(["HELLO", "WORLD"]))
print(np.char.lower("HELLO"))

['hello' 'world']
hello


In [70]:
print(np.char.upper(["hello", "world"]))
print(np.char.upper("hello"))

['HELLO' 'WORLD']
HELLO


In [71]:
print(np.char.split("are you coming the party?"))

['are', 'you', 'coming', 'the', 'party?']


In [76]:
print(np.char.splitlines("are you \ncoming to the party?"))

['are you ', 'coming to the party?']


In [78]:
print(np.char.strip(["nina", "admin", "anaita"], "a"))

['nin' 'dmin' 'nait']


In [79]:
print(np.char.join([":", "-"], ["dmy", "ymd"]))

['d:m:y' 'y-m-d']


In [80]:
print(np.char.replace("He is a good dancer", "is", "was"))

He was a good dancer
