# Array Manipulation

# Array Manipulation - changing shape

In [1]:
import numpy as np

a = np.arange(9)
print(a)
print()

b = a.reshape(3, 3)
print(b)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
print(b)
print()
c = b.flatten()
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2 3 4 5 6 7 8]


In [3]:
c = b.flatten(order = 'F')
print(c)

[0 3 6 1 4 7 2 5 8]


In [4]:
a = np.arange(12).reshape(4, 3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
print(a)
print()
b = np.transpose(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [6]:
b = np.arange(8).reshape(2, 4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [7]:
c = b.reshape(2, 2, 2)
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [8]:
print(c)
print()
np.rollaxis(c, 2, 1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [9]:
np.rollaxis(c,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [10]:
print(c)
print()
np.swapaxes(c, 1, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [11]:
np.swapaxes(c, 2, 1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

# Numpy Arithematic Operations

In [12]:
a = np.arange(9).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
b = np.array([[10, 10, 10], [10, 10, 10], [10, 10, 10]])
print(b)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [14]:
np.add(a, b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
print(a)
print()
print(b)
print()
print(np.subtract(a, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


In [16]:
print(a)
print()
print(b)
print()
print(np.multiply(a, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [17]:
print(a)
print()
print(b)
print()
print(np.divide(a, b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[10 10 10]
 [10 10 10]
 [10 10 10]]

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


# Slicing

In [18]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [19]:
print(a[4:])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [20]:
# 2: first indexId I want
# 9: first indexId I don't want
# 2: step = 2
print(a)
print()
s = slice(2, 9, 2)
print(a[s])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[2 4 6 8]


# Iterating Over Array

In [23]:
a = np.arange(0, 45, 5)
print(a)
a = a.reshape(3,3)
print(a)

[ 0  5 10 15 20 25 30 35 40]
[[ 0  5 10]
 [15 20 25]
 [30 35 40]]


In [24]:
print(a)
for x in np.nditer(a):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40


# Iteration order (c-style and f-style)

In [26]:
print(a)
for x in np.nditer(a, order = "C"):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40


In [27]:
print(a)
for x in np.nditer(a, order = "F"):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
15
30
5
20
35
10
25
40


In [38]:
a = np.array([[1, 2], [3, 4]])
print(a)
print("---------------------")
b = np.array([[5, 6], [7, 8]])
print(b)
print("\n")
print(np.concatenate((a, b)))
print("\n")
print(np.concatenate(([1, 2], [3, 4])))

[[1 2]
 [3 4]]
---------------------
[[5 6]
 [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[1 2 3 4]
